# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Staging - Build & Deploy

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy environment file
        run: cp .env.staging .env

      - name: Check PHP version before setup
        run: php -v

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check PHP version after setup
        run: php -v

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Check PHP version before setup
        run: php -v

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check PHP version after setup
        run: php -v

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DEAEBB5CFB2A4E9690C508FF696BA052 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FCBB254ED21F45E696D002D2BDFE9BB9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_626CB116FE2E46CA9009EB426892F16F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'mavericks-st'
          slot-name: 'Production'
          package: .

      - name: Verify database configuration
        run: php artisan tinker --execute="print_r(config('database.connections.pgsql'))"
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION_ST }}
          DB_HOST: ${{ secrets.DB_HOST_ST }}
          DB_PORT: ${{ secrets.DB_PORT_ST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE_ST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME_ST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_ST }}

      - name: List tables before migration
        run: php artisan tinker --execute="\DB::select('SHOW TABLES');"
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION_ST }}
          DB_HOST: ${{ secrets.DB_HOST_ST }}
          DB_PORT: ${{ secrets.DB_PORT_ST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE_ST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME_ST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_ST }}

      - name: Run migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION_ST }}
          DB_HOST: ${{ secrets.DB_HOST_ST }}
          DB_PORT: ${{ secrets.DB_PORT_ST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE_ST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME_ST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_ST }}

      - name: List tables after migration
        run: php artisan tinker --execute="\DB::select('SHOW TABLES');"
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION_ST }}
          DB_HOST: ${{ secrets.DB_HOST_ST }}
          DB_PORT: ${{ secrets.DB_PORT_ST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE_ST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME_ST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_ST }}
